### ISSUE TITLE
Unable to Change Role Permissions

### ISSUE THREAD

**Issue by projectwehelp** [glewe/ci4-auth#18]
Can't seem find a way to  change set  user permissions in  'Roles' page nor add new roles:

<img width="1193" alt="Screenshot 2023-05-16 at 11 28 35 AM" src="https://github.com/glewe/ci4-auth/assets/78574989/2f251002-75b3-48cc-b5ee-be380d653fcb">

**Comment by glewe** [comment]
Hi @projectwehelp ,
I am not sure that I understand you right. The screenshot shows the role edit page. You can assign permissions to the role there. Users in that role will automatically inherit the permissions.
You can add a role from the role list page.
Can you elaborate more what did not work on your end?
Best regards,
George

**Comment by projectwehelp** [comment]
I meant  from admin pages:
a)  not able to  remove any permission once added. 
b) not able to add a new permission to the list of permissions

**Comment by glewe** [comment]
Hi @projectwehelp ,
the permission to manage permissions is not assigned to any role, group or user when you seed the CI4-Auth database. But you can assign it in the GUI afterwards. E.g., select the Administrator role and assign the permissions

- permission.create
- permission.delete
- permission.edit
- permission.view

That gives you the GUI pages to manage them.
Let me know if that worked.

Best regards,
George

_(Note: Release 3.1.1 does not validate a dot in a permission name. I fixed that already in the PermissionController. The fix is pushed though so you can replace the file.)_
